# Generated by Django 5.1.1 on 2024-09-20 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
